# YAML build file
# nx-apphub-cli 2025 (c) Nitrux Latinoamericana S.C.

buildinfo:
  name: vim
  version: 2:9.2.0461-1
  binarypath: /usr/bin/vim.basic
  os-target: 6.1.0
  distrorepo:
    - distro: debian-snapshot
      snapshot: 20260725T202958Z
      release: testing
      arch: arm64
      components:
        - main
  deps:
    - libacl1
    - libgpm2
    - libselinux1
    - libsodium23
    - libtinfo6
    - vim
    - vim-common
    - vim-runtime
  runtime: uruntime

apprunconf:
  exec: /usr/bin/vim.basic
  setpath: /usr/bin
  setlibpath: /usr/lib
  envvars: {}
  prebuild-commands: []

sandbox:
  type: firejail
  name: vim
  aa-profile: none

integration:
  type: cli
