# YAML build file
# nx-apphub-cli 2025 (c) Nitrux Latinoamericana S.C.

buildinfo:
  name: plasma-desktop
  version: 6.3.6-2
  binarypath: /usr/bin/plasmashell
  distrorepo:
    - distro: debian
      release: testing
      arch: arm64    
  deps:
    - kactivitymanagerd
    - kded6
    - kwin-common
    - kwin-wayland
    - libaccounts-glib0
    - libaccounts-qt6-1
    - libibus-1.0-5
    - libkaccounts6-2
    - libkglobalaccelmodel6
    - libplasma5support6
    - libscim8v5
    - libsignon-qt6-1
    - milou
    - plasma-desktop
    - plasma-desktop-data
    - plasma-workspace
    - plasma-workspace-data
    - x11-utils
    - x11-xserver-utils
  runtime: uruntime

apprunconf:
  setpath: "/usr/bin"
  setlibpath: "/usr/lib"
  exec: "/usr/bin/plasma-startup-wrapper"
  envvars:
    KDEDIRS: "$APPDIR/usr"
    PLASMA_USE_SYSTEMD: "0"
    QT_QPA_PLATFORM: "wayland;xcb"
    QT_QPA_PLATFORMTHEME: ""
    QT_PLUGIN_PATH: "$APPDIR/usr/lib/aarch64-linux-gnu/qt5/plugins:$APPDIR/usr/lib/aarch64-linux-gnu/qt6/plugins"
    QT_QML_IMPORT_PATH: "$APPDIR/usr/lib/aarch64-linux-gnu/qt5/qml:$APPDIR/usr/lib/aarch64-linux-gnu/qt6/qml"
    QML_IMPORT_PATH: "$APPDIR/usr/lib/aarch64-linux-gnu/qt6/qml"
    QML2_IMPORT_PATH: "$APPDIR/usr/lib/aarch64-linux-gnu/qt5/qml"
    SESSION_MANAGER: ""
    XKB_CONFIG_ROOT: "$APPDIR/usr/share/X11/xkb"
    XDG_CURRENT_DESKTOP: "KDE"
    KDE_FULL_SESSION: "true"
    KDE_SESSION_VERSION: "6"
    XDG_CONFIG_DIRS: "$HOME/.config/kdedefaults:/etc/xdg"
    XDG_DATA_DIRS: "$APPDIR/usr/share:$XDG_DATA_DIRS"
    DBUS_SESSION_BUS_ADDRESS: "$DBUS_SESSION_BUS_ADDRESS"
    XDG_RUNTIME_DIR: "$XDG_RUNTIME_DIR"
    KSERVICE_FORCE_KDEGLOBALS: "1"
    KDE_APPLICATIONS_AS_SCOPE: "1"

sandbox:
  type: bwrap
  ro-root: true
  dev: true
  proc: true
  bind:
    - "~/.local/share/plasma-appimage:~/.config"
    - "~/.local/share/plasma-appimage-data:~/.local/share"
    - "~/.cache/plasma-appimage:~/.cache"
  bind-try:
    - "/tmp/.X11-unix:/tmp/.X11-unix"
    - "/run/user:/run/user"
  ro-bind-try:
    - "~/.config/kdedefaults:~/.config/kdedefaults"

integration:
  type: gui
