# YAML build file
# nx-apphub-cli 2025 (c) Nitrux Latinoamericana S.C.

buildinfo:
  name: mc
  version: latest
  binarypath: /usr/bin/mc
  distrorepo:
    - distro: debian
      release: testing
      arch: amd64
  deps:
    - mc
    - libc6
    - libext2fs2t64
    - libglib2.0-0t64
    - libgpm2
    - libslang2
    - libssh2-1t64
    - mc-data
  usewrapper: false

apprunconf:
  setpath: "/usr/bin"
  setlibpath: "/usr/lib"
  exec: "/usr/bin/mc"
