# YAML build file
# nx-apphub-cli 2025 (c) Nitrux Latinoamericana S.C.

buildinfo:
  name: fiery
  version: 4.0.1-1
  binarypath: /usr/bin/fiery
  distrorepo:
    - distro: nitrux
      release: trixie
      arch: amd64
    - distro: debian
      release: testing
      arch: amd64
  deps:
    - fiery-git
    - kio-extras
    - libqt6webenginecore6
    - libqt6webenginecore6-bin
    - libqt6webenginequick6
    - mauikit-filebrowsing-git
    - mauikit-git
    - qml6-module-qtcore
    - qml6-module-qtquick-effects
    - qml6-module-qtwebengine
    - libqt6sql6
  usewrapper: false

apprunconf:
  setpath: "/usr/bin"
  setlibpath: "/usr/lib"
  exec: "/usr/bin/fiery"
  prebuild_commands:
    - "cd $APPDIR/usr/lib/x86_64-linux-gnu && ln -sv libMauiKit4.so.4.0.1 libMauiKit4.so.4 && cd -"
