# YAML build file
# nx-apphub-cli 2025 (c) Nitrux Latinoamericana S.C.

buildinfo:
  name: fiery
  version: 4.0.1-1
  binarypath: /usr/bin/fiery
  distrorepo:
    - distro: nitrux
      release: trixie
      arch: amd64
    - distro: debian
      release: testing
      arch: amd64
  deps:
    - fiery-git
    - kio-extras
    - libc6
    - libkf6coreaddons6
    - libkf6i18n6
    - libkf6iconthemes6
    - libkf6notifications6
    - libkf6windowsystem6
    - libqt6core6t64
    - libqt6gui6
    - libqt6multimedia6
    - libqt6multimediawidgets6
    - libqt6qml6
    - libqt6quick6
    - libqt6quickcontrols2-6
    - libqt6quickshapes6
    - libqt6spatialaudio6
    - libqt6sql6
    - libqt6svg6
    - libqt6svgwidgets6
    - libqt6webenginecore6
    - libqt6webenginecore6-bin
    - libqt6webenginequick6
    - libqt6widgets6
    - maui-manager-git
    - mauikit-filebrowsing-git
    - mauikit-git
    - qml6-module-org-kde-kirigami
    - qml6-module-qtcore
    - qml6-module-qtmultimedia
    - qml6-module-qtquick-controls
    - qml6-module-qtquick-effects
    - qml6-module-qtquick-shapes
    - qml6-module-qtquick3d-spatialaudio
    - qml6-module-qtwebengine
  usewrapper: false

apprunconf:
  setpath: "/usr/bin"
  setlibpath: "/usr/lib"
  exec: "/usr/bin/fiery"
  prebuild_commands:
    - "cd $APPDIR/usr/lib/x86_64-linux-gnu && ln -sv libMauiKit4.so.4.0.1 libMauiKit4.so.4 && cd -"
