# YAML build file
# nx-apphub-cli 2025 (c) Nitrux Latinoamericana S.C.

buildinfo:
  name: maui-fiery
  version: 2.0.0-0
  binarypath: /usr/bin/fiery
  distrorepo:
    - distro: kde-neon
      release: noble
      arch: amd64
  deps:
    - cask-server
    - libmauikit
    - libmauikitfilebrowsing4
    - libmauiman
    - mauiman
    - qml6-module-org-kde-purpose
    - qml6-module-org-maui-mauikit
    - qml6-module-org-maui-mauikit-filebrowsing
    - qml6-module-qtquick-shapes
  usewrapper: false

apprunconf:
  setpath: "/usr/bin"
  setlibpath: "/usr/lib"
  exec: "/usr/bin/fiery"
