# YAML build file
# nx-apphub-cli 2025 (c) Nitrux Latinoamericana S.C.

buildinfo:
  name: fiery
  version: 4.0.1-1
  binarypath: /usr/bin/fiery
  distrorepo:
    - distro: nitrux
      release: trixie
      arch: amd64
    - distro: debian-snapshots
      release: testing
      arch: amd64
  deps:
    - fiery-git
    - kio-extras
    - libasound2-data
    - libasound2t64
    - libatomic1
    - libb2-1
    - libbrotli1
    - libbz2-1.0
    - libcanberra0
    - libcom-err2
    - libcurl3t64-gnutls
    - libdouble-conversion3
    - libdrm2
    - libduktape207
    - libevent-2.1-7t64
    - libexpat1
    - libffi8
    - libfreetype6
    - libgcrypt20
    - libglvnd0
    - libgomp1
    - libgpg-error0
    - libgraphite2-3
    - libgssapi-krb5-2
    - libharfbuzz-subset0
    - libharfbuzz0b
    - libicu72
    - libimobiledevice-1.0-6
    - libimobiledevice-glue-1.0-0
    - libjbig0
    - libjpeg62-turbo
    - libk5crypto3
    - libkf6archive-data
    - libkf6archive6
    - libkf6auth-data
    - libkf6authcore6
    - libkf6bookmarks-data
    - libkf6bookmarks6
    - libkf6bookmarkswidgets6
    - libkf6breezeicons6
    - libkf6codecs-data
    - libkf6codecs6
    - libkf6colorscheme-data
    - libkf6colorscheme6
    - libkf6completion6
    - libkf6config-data
    - libkf6configcore6
    - libkf6configgui6
    - libkf6coreaddons6
    - libkf6crash6
    - libkf6guiaddons-data
    - libkf6guiaddons6
    - libkf6i18n6
    - libkf6iconthemes-data
    - libkf6iconthemes6
    - libkf6iconwidgets6
    - libkf6itemviews-data
    - libkf6itemviews6
    - libkf6jobwidgets6
    - libkf6kiocore6
    - libkf6kiofilewidgets6
    - libkf6kiogui6
    - libkf6kiowidgets6
    - libkf6notifications6
    - libkf6service-bin
    - libkf6service6
    - libkf6solid-data
    - libkf6solid6
    - libkf6widgetsaddons-data
    - libkf6widgetsaddons6
    - libkf6windowsystem-data
    - libkf6windowsystem6
    - libkirigami-data
    - libkirigami6
    - libkirigamidelegates6
    - libkirigamidialogs6
    - libkirigamilayouts6
    - libkirigamiplatform6
    - libkirigamiprimitives6
    - libkirigamiprivate6
    - libkrb5-3
    - libkrb5support0
    - liblcms2-2
    - libldap-2.5-0
    - liblerc4
    - libltdl7
    - liblzma5
    - libmd4c0
    - libminizip1t64
    - libnspr4
    - libnss3
    - libogg0
    - libopengl0
    - libopenjp2-7
    - libopus0
    - libpcre2-16-0
    - libpcre2-8-0
    - libplist-2.0-4
    - libpng16-16t64
    - libproxy1v5
    - libqt6core6t64
    - libqt6dbus6
    - libqt6gui6
    - libqt6multimedia6
    - libqt6multimediawidgets6
    - libqt6network6
    - libqt6opengl6
    - libqt6positioning6
    - libqt6qml6
    - libqt6qmlmodels6
    - libqt6qmlworkerscript6
    - libqt6quick6
    - libqt6quickcontrols2-6
    - libqt6quickshapes6
    - libqt6quicktemplates2-6
    - libqt6spatialaudio6
    - libqt6sql6
    - libqt6svg6
    - libqt6svgwidgets6
    - libqt6waylandclient6
    - libqt6webchannel6
    - libqt6webchannelquick6
    - libqt6webengine6-data
    - libqt6webenginecore6
    - libqt6webenginecore6-bin
    - libqt6webenginequick6
    - libqt6webenginewidgets6
    - libqt6widgets6
    - libqt6xml6
    - libsharpyuv0
    - libsnappy1v5
    - libssh2-1t64
    - libssl3t64
    - libtdb1
    - libtiff6
    - libusbmuxd-2.0-7
    - libvorbis0a
    - libvorbisfile3
    - libwayland-client0
    - libwayland-cursor0
    - libwayland-server0
    - libwebp7
    - libwebpdemux2
    - libwebpmux3
    - libx11-6
    - libx11-data
    - libxau6
    - libxcb-cursor0
    - libxcb-keysyms1
    - libxcb-res0
    - libxcb1
    - libxcomposite1
    - libxdamage1
    - libxdmcp6
    - libxext6
    - libxfixes3
    - libxkbcommon0
    - libxkbfile1
    - libxml2
    - libxrandr2
    - libxrender1
    - libxslt1.1
    - libxtst6
    - libzstd1
    - maui-manager-git
    - mauikit-filebrowsing-git
    - mauikit-git
    - qml6-module-org-kde-kirigami
    - qml6-module-qt-labs-folderlistmodel
    - qml6-module-qtcore
    - qml6-module-qtmultimedia
    - qml6-module-qtqml
    - qml6-module-qtqml-models
    - qml6-module-qtqml-workerscript
    - qml6-module-qtquick
    - qml6-module-qtquick-controls
    - qml6-module-qtquick-dialogs
    - qml6-module-qtquick-effects
    - qml6-module-qtquick-layouts
    - qml6-module-qtquick-shapes
    - qml6-module-qtquick-templates
    - qml6-module-qtquick-window
    - qml6-module-qtquick3d-spatialaudio
    - qml6-module-qtwebengine
    - qml6-module-qtwebengine-controlsdelegates
    - qt6-wayland
    - zlib1g
  usewrapper: false

apprunconf:
  setpath: "/usr/bin"
  setlibpath: "/usr/lib"
  exec: "/usr/bin/fiery"
  envvars:
    QT_QPA_PLATFORM: "wayland;xcb"
    QT_PLUGIN_PATH: "$APPDIR/usr/lib/x86_64-linux-gnu/qt5/plugins:$APPDIR/usr/lib/x86_64-linux-gnu/qt6/plugins:$QT_PLUGIN_PATH"
    QT_QML_IMPORT_PATH: "$APPDIR/usr/lib/x86_64-linux-gnu/qt5/qml:$APPDIR/usr/lib/x86_64-linux-gnu/qt6/qml:$QT_QML_IMPORT_PATH"
    QML_IMPORT_PATH: "$APPDIR/usr/lib/x86_64-linux-gnu/qt6/qml:$QML_IMPORT_PATH"
    QML2_IMPORT_PATH: "$APPDIR/usr/lib/x86_64-linux-gnu/qt5/qml:$QML2_IMPORT_PATH"
    QTWEBENGINEPROCESS_PATH: "$APPDIR/usr/lib/qt6/libexec/QtWebEngineProcess"
    QTWEBENGINE_RESOURCES_PATH: "$APPDIR/usr/share/qt6/resources"
  prebuild_commands:
    - "cd $APPDIR/usr/lib/x86_64-linux-gnu && ln -sv libMauiKit4.so.4.0.1 libMauiKit4.so.4 && cd -"
    - "cd $APPDIR/usr/lib/x86_64-linux-gnu && ln -sv libMauiMan4.so.4.0.1 libMauiMan4.so.4 && cd -"
    - "cd $APPDIR/usr/lib/x86_64-linux-gnu && ln -sv libMauiKitFileBrowsing4.so.4.0.1 libMauiKitFileBrowsing4.so.4 && cd -"
