# YAML build file
# nx-apphub-cli 2025 (c) Nitrux Latinoamericana S.C.

buildinfo:
  name: nano
  version: 8.3-1
  binarypath: /usr/bin/nano
  distrorepo:
    - distro: debian
      release: testing
      arch: amd64
  deps:
    - libncursesw6
    - libtinfo6
    - nano

apprunconf:
  setpath: "/usr/bin"
  setlibpath: "/usr/lib"
  exec: "/usr/bin/nano"
