# YAML build file
# nx-apphub-cli 2025 (c) Nitrux Latinoamericana S.C.

buildinfo:
  name: nano
  version: 7.2-1+deb12u1
  binarypath: /bin/nano
  distrorepo:
    - distro: debian
      release: stable
      arch: amd64
  deps:
    - nano
    - libc6
    - libncursesw6
    - libtinfo6
  usewrapper: false

apprunconf:
  setpath: "/bin"
  setlibpath: "/lib"
  exec: "/bin/nano"
