# YAML build file
# nx-apphub-cli 2025 (c) Nitrux Latinoamericana S.C.

buildinfo:
  name: fastfetch
  version: 2.63.1
  binarypath: /usr/bin/fastfetch
  os-target: 6.1.0
  distrorepo:
    - distro: nitrux
      release: duke
      arch: arm64
  deps:
    - fastfetch
  runtime: uruntime

apprunconf:
  setpath: "/usr/bin"
  setlibpath: "/usr/lib"
  exec: "/usr/bin/fastfetch"
  envvars: {}
  prebuild-commands: []

sandbox:
  type: bwrap
  ro-root: true
  dev: true
  proc: true
  die-with-parent: true
  bind:
    - "$HOME:$HOME"
    - ~/.config:~/.config
    - ~/.local:~/.local
    - "$XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR"
    - /dev/shm:/dev/shm
    - /dev/dri/renderD128:/dev/dri/renderD128
  bind-try:
    - /run/dbus:/run/dbus
    - /run/udev:/run/udev
    - /tmp:/tmp
  bwrap-env:
    - HOME: "$HOME"
    - LANG: "en_US.UTF-8"
    - XDG_RUNTIME_DIR: "$XDG_RUNTIME_DIR"
    - WAYLAND_DISPLAY: "$WAYLAND_DISPLAY"
    - DBUS_SESSION_BUS_ADDRESS: "$DBUS_SESSION_BUS_ADDRESS"
    - DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/run/dbus/system_bus_socket"

integration:
  type: cli
