# YAML build file
# nx-apphub-cli 2025 (c) Nitrux Latinoamericana S.C.

buildinfo:
  name: vim
  version: 2:9.1.1230-1
  binarypath: /usr/bin/vim.basic
  distrorepo:
    - distro: debian
      release: unstable
      arch: amd64
  deps:
    - libacl1
    - libgpm2
    - libselinux1
    - libsodium23
    - libtinfo6
    - vim
    - vim-common
    - vim-runtime
  runtime: uruntime

apprunconf:
  exec: /usr/bin/vim.basic
  setpath: /usr/bin
  setlibpath: /usr/lib
  envvars: {}
  prebuild_commands: []

sandbox:
  type: firejail
  name: vim
  aa_profile: none

integration:
  type: cli
