# YAML build file
# nx-apphub-cli 2025 (c) Nitrux Latinoamericana S.C.

buildinfo:
  name: inkscape
  version: 1:1.4.1+202503302257+93de688d07~ubuntu24.10.1 
  binarypath: /usr/bin/inkscape
  distrorepo:
    base:
      - distro: ubuntu
        release: oracular
        arch: amd64
    ppas:
      - id: inkscape-dev
        ppa: inkscape.dev/stable
        distro: ubuntu
        release: oracular
        arch: amd64
  deps:
    - inkscape
    - lib2geom1.2.0t64
    - libatkmm-1.6-1v5
    - libboost-filesystem1.83.0
    - libcairo-gobject2
    - libcairo2
    - libcairomm-1.0-1v5
    - libcdr-0.1-1
    - libdouble-conversion3
    - libfontconfig1
    - libfreetype6
    - libgc1
    - libgdk-pixbuf-2.0-0
    - libglib2.0-0t64
    - libglibmm-2.4-1t64
    - libgomp1
    - libgsl28
    - libgspell-1-2
    - libgtk-3-0t64
    - libgtkmm-3.0-1t64
    - libharfbuzz0b
    - libjpeg8
    - liblcms2-2
    - libmagick++-6.q16-9t64
    - libpango-1.0-0
    - libpangocairo-1.0-0
    - libpangoft2-1.0-0
    - libpangomm-1.4-1v5
    - libpng16-16t64
    - libpoppler-glib8t64
    - libpoppler140
    - libpotrace0
    - libreadline8t64
    - librevenge-0.0-0
    - librsvg2-common
    - libsigc++-2.0-0v5
    - libsoup-2.4-1
    - libstdc++6
    - libvisio-0.1-1
    - libwpg-0.3-3
    - libx11-6
    - libxml2
    - libxslt1.1
    - python3
    - zlib1g
  usewrapper: false

apprunconf:
  setpath: "/usr/bin"
  setlibpath: "/usr/lib"
  exec: "/usr/bin/inkscape"
