# YAML build file
# nx-apphub-cli 2025 (c) Nitrux Latinoamericana S.C.

buildinfo:
  name: vvave
  version: 4.0.2-1
  binarypath: /usr/bin/vvave
  distrorepo:
    - distro: debian
      release: testing
      arch: amd64    
    - distro: nitrux
      release: forky
      arch: amd64
  deps:
    - kio-extras
    - kio6
    - libappimage1.0abi1t64
    - libasound2t64
    - libasyncns0
    - libavcodec61
    - libavformat61
    - libavutil59
    - libb2-1
    - libboost-filesystem1.83.0
    - libbz2-1.0
    - libcanberra0
    - libcurl3t64-gnutls
    - libdeflate0
    - libdouble-conversion3
    - libduktape207
    - libevent-2.1-7t64
    - libffi8
    - libflac14
    - libfontconfig1
    - libfreetype6
    - libgomp1
    - libgraphite2-3
    - libharfbuzz-subset0
    - libharfbuzz0b
    - libice6
    - libicu76
    - libimobiledevice-1.0-6
    - libimobiledevice-glue-1.0-0
    - libinput10
    - libkdsoap-qt6-2
    - libkdsoapwsdiscoveryclient0
    - libkexiv2qt6-0
    - libkf6archive6
    - libkf6authcore6
    - libkf6bookmarks6
    - libkf6bookmarkswidgets6
    - libkf6breezeicons6
    - libkf6codecs6
    - libkf6colorscheme6
    - libkf6completion6
    - libkf6configcore6
    - libkf6configgui6
    - libkf6configwidgets6
    - libkf6coreaddons6
    - libkf6crash6
    - libkf6dbusaddons6
    - libkf6dnssd6
    - libkf6doctools6
    - libkf6globalaccel6
    - libkf6guiaddons6
    - libkf6i18n6
    - libkf6i18nqml6
    - libkf6iconthemes6
    - libkf6iconwidgets6
    - libkf6itemviews6
    - libkf6jobwidgets6
    - libkf6kcmutils6
    - libkf6kcmutilscore6
    - libkf6kcmutilsquick6
    - libkf6kiocore6
    - libkf6kiofilewidgets6
    - libkf6kiogui6
    - libkf6kiowidgets6
    - libkf6notifications6
    - libkf6pty6
    - libkf6service6
    - libkf6solid6
    - libkf6sonnetcore6
    - libkf6sonnetui6
    - libkf6syntaxhighlighting6
    - libkf6textwidgets6
    - libkf6wallet6
    - libkf6widgetsaddons6
    - libkf6windowsystem6
    - libkf6xmlgui6
    - libkirigami6
    - libkirigamidelegates6
    - libkirigamidialogs6
    - libkirigamilayouts6
    - libkirigamiplatform6
    - libkirigamiprimitives6
    - libkirigamiprivate6
    - liblcms2-2
    - libldap2
    - liblerc4
    - libltdl7
    - libmd4c0
    - libminizip1t64
    - libmp3lame0
    - libmpg123-0t64
    - libmtdev1t64
    - libmtp9t64
    - libnghttp3-9
    - libngtcp2-16
    - libngtcp2-crypto-gnutls8
    - libnspr4
    - libnss3
    - libogg0
    - libopenexr-3-1-30
    - libopus0
    - libpcre2-16-0
    - libphonon4qt6-4t64
    - libplasmaactivities6
    - libplasmaactivitiesstats1
    - libplist-2.0-4
    - libpng16-16t64
    - libpolkit-qt6-1-1
    - libproxy1v5
    - libpulse0
    - libqt6core5compat6
    - libqt6core6t64
    - libqt6dbus6
    - libqt6gui6
    - libqt6multimedia6
    - libqt6network6
    - libqt6opengl6
    - libqt6positioning6
    - libqt6printsupport6
    - libqt6qml6
    - libqt6qmlmeta6
    - libqt6qmlmodels6
    - libqt6qmlworkerscript6
    - libqt6quick6
    - libqt6quickcontrols2-6
    - libqt6quickshapes6
    - libqt6quicktemplates2-6
    - libqt6quickwidgets6
    - libqt6sql6
    - libqt6sql6-sqlite
    - libqt6svg6
    - libqt6texttospeech6
    - libqt6waylandclient6
    - libqt6waylandcompositor6
    - libqt6widgets6
    - libqt6wlshellintegration6
    - libqt6xml6
    - librtmp1
    - libsasl2-2
    - libsharpyuv0
    - libsm6
    - libsmbclient0
    - libsnappy1v5
    - libsndfile1
    - libsqlite3-0
    - libssh-4
    - libssh2-1t64
    - libswresample5
    - libswscale8
    - libtag2
    - libtdb1
    - libtiff6
    - libts0t64
    - libusbmuxd-2.0-7
    - libvorbis0a
    - libvorbisenc2
    - libvorbisfile3
    - libxcb-cursor0
    - libxcb-icccm4
    - libxcb-image0
    - libxcb-keysyms1
    - libxcb-render-util0
    - libxcb-res0
    - libxcb-shape0
    - libxcb-xinput0
    - libxcb-xkb1
    - libxcomposite1
    - libxdamage1
    - libxfixes3
    - libxkbcommon-x11-0
    - libxkbcommon0
    - libxkbfile1
    - libxml2
    - libxslt1.1
    - maui-manager
    - mauikit
    - mauikit-archiver
    - mauikit-filebrowsing
    - qml6-module-org-kde-kirigami
    - qml6-module-org-kde-sonnet
    - qml6-module-qtcore
    - qml6-module-qtmultimedia
    - qml6-module-qtqml
    - qml6-module-qtqml-workerscript
    - qml6-module-qtquick-controls
    - qml6-module-qtquick-effects
    - qml6-module-qtquick-layouts
    - qml6-module-qtquick-shapes
    - qml6-module-qtquick-templates
    - qml6-module-qtquick-tooling
    - qml6-module-qtquick-window
    - qt6-gtk-platformtheme
    - qt6-svg-plugins
    - qt6-wayland
    - vvave
    - xkb-data
  runtime: uruntime

apprunconf:
  setpath: "/usr/bin"
  setlibpath: "/usr/lib"
  exec: "/usr/bin/vvave"
  envvars:
    QT_QPA_PLATFORM: "wayland;xcb"
    QT_PLUGIN_PATH: "$APPDIR/usr/lib/x86_64-linux-gnu/qt5/plugins:$APPDIR/usr/lib/x86_64-linux-gnu/qt6/plugins"
    QT_QML_IMPORT_PATH: "$APPDIR/usr/lib/x86_64-linux-gnu/qt5/qml:$APPDIR/usr/lib/x86_64-linux-gnu/qt6/qml"
    QML_IMPORT_PATH: "$APPDIR/usr/lib/x86_64-linux-gnu/qt6/qml"
    QML2_IMPORT_PATH: "$APPDIR/usr/lib/x86_64-linux-gnu/qt5/qml"
    SESSION_MANAGER: ""
    XKB_CONFIG_ROOT: "$APPDIR/usr/share/X11/xkb"
  prebuild_commands:
    - "cd $APPDIR/usr/lib/x86_64-linux-gnu && ln -sv libMauiKit4.so.4.0.2 libMauiKit4.so.4 && cd -"
    - "cd $APPDIR/usr/lib/x86_64-linux-gnu && ln -sv libMauiMan4.so.4.0.2 libMauiMan4.so.4 && cd -"
    - "cd $APPDIR/usr/lib/x86_64-linux-gnu && ln -sv libMauiKitFileBrowsing4.so.4.0.2 libMauiKitFileBrowsing4.so.4 && cd -"
    - "rm -f $APPDIR/usr/share/metainfo/org.kde.vvave.appdata.xml"

sandbox:
  type: bwrap
  dev: true
  proc: true
  tmpfs: true
  unshare-user: true
  unshare-uts: true
  cap-drop-all: true
  die-with-parent: true
  bind:
    - "$HOME:$HOME"
    - ~/.config:~/.config
    - ~/.local:~/.local
    - "$XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR"
    - /dev/shm:/dev/shm
    - /dev/dri:/dev/dri
  ro-bind:
    - "$APPDIR:$APPDIR"
    - /lib:/lib
    - /lib64:/lib64
    - /usr:/usr
    - /etc/fonts:/etc/fonts
    - /etc/xdg:/etc/xdg
    - /etc/alternatives:/etc/alternatives
  bwrap_env:
    - HOME: "$HOME"
    - LANG: "en_US.UTF-8"
    - XDG_RUNTIME_DIR: "$XDG_RUNTIME_DIR"
    - WAYLAND_DISPLAY: "$WAYLAND_DISPLAY"
  bwrap_unset-env:
    - DISPLAY

integration:
  type: gui
