# YAML build file
# nx-apphub-cli 2025 (c) Nitrux Latinoamericana S.C.

buildinfo:
  name: nano
  version: latest
  binarypath: /usr/bin/nano
  distrorepo:
    - distro: debian
      release: testing
      arch: amd64
  deps:
    - nano
    - libc6
    - libncursesw6
    - libtinfo6
  usewrapper: false

apprunconf:
  setpath: "/usr/bin"
  setlibpath: "/usr/lib"
  exec: "/usr/bin/nano"
