# YAML build file
# nx-apphub-cli 2025 (c) Nitrux Latinoamericana S.C.

buildinfo:
  name: strike
  version: 2.0.1-1
  binarypath: /usr/bin/strike
  distrorepo:
    - distro: debian
      release: testing
      arch: amd64    
    - distro: nitrux
      release: forky
      arch: amd64
  deps:
    - strike
  runtime: uruntime

apprunconf:
  setpath: "/usr/bin"
  setlibpath: "/usr/lib"
  exec: "/usr/bin/strike"
  envvars:
    QT_QPA_PLATFORM: "wayland;xcb"
    QT_QPA_PLATFORMTHEME: ""
    QT_PLUGIN_PATH: "$APPDIR/usr/lib/aarch64-linux-gnu/qt5/plugins:$APPDIR/usr/lib/aarch64-linux-gnu/qt6/plugins"
    QT_QML_IMPORT_PATH: "$APPDIR/usr/lib/aarch64-linux-gnu/qt5/qml:$APPDIR/usr/lib/aarch64-linux-gnu/qt6/qml"
    QML_IMPORT_PATH: "$APPDIR/usr/lib/aarch64-linux-gnu/qt6/qml"
    QML2_IMPORT_PATH: "$APPDIR/usr/lib/aarch64-linux-gnu/qt5/qml"
    SESSION_MANAGER: ""
    XKB_CONFIG_ROOT: "$APPDIR/usr/share/X11/xkb"
    XDG_CURRENT_DESKTOP: "KDE"
    KDE_FULL_SESSION: "true"
    KDE_SESSION_VERSION: "6"
    XDG_CONFIG_DIRS: "$HOME/.config/kdedefaults:/etc/xdg"
  prebuild_commands: []
sandbox:
  type: bwrap
  dev: true
  proc: true
  tmpfs: true
  unshare-user: true
  unshare-uts: true
  cap-drop-all: true
  die-with-parent: true
  bind:
    - "$HOME:$HOME"
    - ~/.config:~/.config
    - ~/.local:~/.local
    - "$XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR"
    - /dev/shm:/dev/shm
    - /dev/dri:/dev/dri
    - /dev/pts:/dev/pts
  ro-bind:
    - "$APPDIR:$APPDIR"
    - /lib:/lib
    - /lib64:/lib64
    - /usr:/usr
    - /bin:/bin
    - /sbin:/sbin
    - /etc/fonts:/etc/fonts
    - /etc/xdg:/etc/xdg
    - /etc/alternatives:/etc/alternatives
    - /etc/passwd:/etc/passwd
    - /etc/group:/etc/group
    - /etc/nsswitch.conf:/etc/nsswitch.conf
    - /etc/shells:/etc/shells
    - /etc/localtime:/etc/localtime
    - /etc/hosts:/etc/hosts
    - /etc/resolv.conf:/etc/resolv.conf
    - /etc/profile:/etc/profile
    - /etc/profile.d:/etc/profile.d
    - /etc/zsh:/etc/zsh
    - /etc/environment:/etc/environment
    - /etc/login.defs:/etc/login.defs
    - /etc/os-release:/etc/os-release
  bwrap_env:
    - HOME: "$HOME"
    - LANG: "en_US.UTF-8"
    - XDG_RUNTIME_DIR: "$XDG_RUNTIME_DIR"
    - WAYLAND_DISPLAY: "$WAYLAND_DISPLAY"
    - TERM: "xterm-256color"
    - PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  bwrap_unset-env:
    - DISPLAY
    - QT_QPA_PLATFORMTHEME

integration:
  type: gui
