# YAML build file
# nx-apphub-cli 2025 (c) Nitrux Latinoamericana S.C.

buildinfo:
  name: inkscape
  version: 1.4-6
  binarypath: /usr/bin/inkscape
  distrorepo:
    - distro: debian
      release: unstable
      arch: arm64
  deps:
    - inkscape
    - libgsl28
    - libpoppler-glib8t64
    - libwpg-0.3-3
    - librevenge-0.0-0
    - libvisio-0.1-1
    - libcdr-0.1-1
    - libpotrace0
    - libgspell-1-3
    - libgtksourceview-4-0
    - lib2geom1.4.0
    - libgslcblas0
    - libwpd-0.10-10
    - libenchant-2-2
    - libaspell15
  runtime: uruntime

apprunconf:
  setpath: "/usr/bin"
  setlibpath: "/usr/lib"
  exec: "/usr/bin/inkscape"
  envvars:
    XKB_CONFIG_ROOT: "$APPDIR/usr/share/X11/xkb"
    XDG_CURRENT_DESKTOP: "KDE"
    KDE_FULL_SESSION: "true"
    KDE_SESSION_VERSION: "6"
    XDG_CONFIG_DIRS: "$HOME/.config/kdedefaults:/etc/xdg"
    FONTCONFIG_PATH: "$APPDIR/etc/fonts"
    LD_LIBRARY_PATH: "$APPDIR/usr/lib/aarch64-linux-gnu/inkscape"
  extra_rpaths:
    - "$ORIGIN/../../usr/lib/aarch64-linux-gnu/inkscape"
  prebuild_commands:
    - "rm -f $APPDIR/usr/share/metainfo/org.inkscape.Inkscape.appdata.xml"

sandbox:
  type: bwrap
  dev: true
  proc: true
  tmpfs: true
  unshare-user: true
  unshare-uts: true
  cap-drop-all: true
  die-with-parent: true
  bind:
    - "$HOME:$HOME"
    - ~/.config:~/.config
    - ~/.local:~/.local
    - "$XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR"
    - /dev/shm:/dev/shm
    - /dev/dri:/dev/dri
  ro-bind:
    - "$APPDIR:$APPDIR"
    - /lib:/lib
    - /lib64:/lib64
    - /usr:/usr
    - /etc/fonts:/etc/fonts
    - /etc/xdg:/etc/xdg
    - /etc/alternatives:/etc/alternatives
  bwrap_env:
    - HOME: "$HOME"
    - LANG: "en_US.UTF-8"
    - XDG_RUNTIME_DIR: "$XDG_RUNTIME_DIR"
    - WAYLAND_DISPLAY: "$WAYLAND_DISPLAY"
  bwrap_unset-env:
    - DISPLAY

integration:
  type: gui
