# YAML build file
# nx-apphub-cli 2025 (c) Nitrux Latinoamericana S.C.

buildinfo:
  name: clip
  version: 4.0.2-1
  binarypath: /usr/bin/clip
  distrorepo:
    - distro: debian
      release: stable
      arch: amd64
    - distro: nitrux
      release: forky
      arch: amd64
  deps:
    - clip
    - libavutil59
    - libavfilter10
    - libavformat61
    - libavcodec61
    - libswscale8
    - libpostproc58
    - libswresample5
    - libpocketsphinx3
    - libsphinxbase3t64
    - libplacebo349
    - libbluray2
    - libvpx9
    - librav1e0.7
    - libtheoraenc1
    - libtheoradec1
    - libx264-164
    - libudfread0
    - qml6-module-qt-labs-settings
    - libblas3
    - liblapack3
  runtime: uruntime

apprunconf:
  setpath: "/usr/bin"
  setlibpath: "/usr/lib"
  exec: "/usr/bin/clip"
  envvars:
    QT_QPA_PLATFORM: "wayland;xcb"
    QT_QPA_PLATFORMTHEME: ""
    QT_PLUGIN_PATH: "$APPDIR/usr/lib/x86_64-linux-gnu/qt5/plugins:$APPDIR/usr/lib/x86_64-linux-gnu/qt6/plugins"
    QT_QML_IMPORT_PATH: "$APPDIR/usr/lib/x86_64-linux-gnu/qt5/qml:$APPDIR/usr/lib/x86_64-linux-gnu/qt6/qml"
    QML_IMPORT_PATH: "$APPDIR/usr/lib/x86_64-linux-gnu/qt6/qml"
    QML2_IMPORT_PATH: "$APPDIR/usr/lib/x86_64-linux-gnu/qt5/qml"
    SESSION_MANAGER: ""
    XKB_CONFIG_ROOT: "$APPDIR/usr/share/X11/xkb"
    XDG_CURRENT_DESKTOP: "KDE"
    KDE_FULL_SESSION: "true"
    KDE_SESSION_VERSION: "6"
    XDG_CONFIG_DIRS: "$HOME/.config/kdedefaults:/etc/xdg"
  extra_rpaths:
    - "$ORIGIN/../../usr/lib/x86_64-linux-gnu/blas"
    - "$ORIGIN/../../usr/lib/x86_64-linux-gnu/lapack"
  prebuild_commands:
    - "rm -f $APPDIR/usr/share/metainfo/org.kde.clip.appdata.xml"

sandbox:
  type: bwrap
  dev: true
  proc: true
  tmpfs: true
  unshare-user: true
  unshare-uts: true
  cap-drop-all: true
  die-with-parent: true
  bind:
    - "$HOME:$HOME"
    - ~/.config:~/.config
    - ~/.local:~/.local
    - "$XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR"
    - /dev/shm:/dev/shm
    - /dev/dri:/dev/dri
  ro-bind:
    - "$APPDIR:$APPDIR"
    - /lib:/lib
    - /lib64:/lib64
    - /usr:/usr
    - /bin:/bin
    - /sbin:/sbin
    - /etc/fonts:/etc/fonts
    - /etc/xdg:/etc/xdg
  bwrap_env:
    - HOME: "$HOME"
    - LANG: "en_US.UTF-8"
    - XDG_RUNTIME_DIR: "$XDG_RUNTIME_DIR"
    - WAYLAND_DISPLAY: "$WAYLAND_DISPLAY"
    - PATH: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  bwrap_unset-env:
    - DISPLAY
    - QT_QPA_PLATFORMTHEME

integration:
  type: gui
