# YAML build file
# nx-apphub-cli 2025 (c) Nitrux Latinoamericana S.C.

buildinfo:
  name: vvave
  version: 4.0.2-1
  binarypath: /usr/bin/vvave
  distrorepo:
    - distro: debian
      release: testing
      arch: arm64    
    - distro: nitrux
      release: forky
      arch: arm64
  deps:
    - kio-extras
    - kio6
    - libaom3
    - libappimage1.0abi1t64
    - libarchive13t64
    - libasound2t64
    - libasyncns0
    - libavcodec61
    - libavformat61
    - libavutil59
    - libb2-1
    - libbluray3
    - libboost-filesystem1.83.0
    - libbz2-1.0
    - libcanberra0
    - libchromaprint1
    - libcjson1
    - libcodec2-1.2
    - libcurl3t64-gnutls
    - libdeflate0
    - libdouble-conversion3
    - libduktape207
    - libdvdnav4
    - libdvdread8t64
    - libevdev2
    - libevent-2.1-7t64
    - libexiv2-28
    - libffi8
    - libflac14
    - libfontconfig1
    - libfreetype6
    - libgme0
    - libgomp1
    - libgraphite2-3
    - libgsm1
    - libgssdp-1.6-0
    - libgstreamer-gl1.0-0
    - libgstreamer-plugins-bad1.0-0
    - libgstreamer-plugins-base1.0-0
    - libgstreamer1.0-0
    - libgudev-1.0-0
    - libgupnp-1.6-0
    - libgupnp-igd-1.6-0
    - libharfbuzz-subset0
    - libharfbuzz0b
    - libhwy1t64
    - libice6
    - libicu76
    - libimath-3-1-29t64
    - libimobiledevice-1.0-6
    - libimobiledevice-glue-1.0-0
    - libinih1
    - libinireader0
    - libinput10
    - libjxl0.11
    - libkdsoap-qt6-2
    - libkdsoapwsdiscoveryclient0
    - libkexiv2qt6-0
    - libkf6archive6
    - libkf6authcore6
    - libkf6bookmarks6
    - libkf6bookmarkswidgets6
    - libkf6breezeicons6
    - libkf6codecs6
    - libkf6colorscheme6
    - libkf6completion6
    - libkf6configcore6
    - libkf6configgui6
    - libkf6configwidgets6
    - libkf6coreaddons6
    - libkf6crash6
    - libkf6dbusaddons6
    - libkf6dnssd6
    - libkf6doctools6
    - libkf6globalaccel6
    - libkf6guiaddons6
    - libkf6i18n6
    - libkf6i18nqml6
    - libkf6iconthemes6
    - libkf6iconwidgets6
    - libkf6itemviews6
    - libkf6jobwidgets6
    - libkf6kcmutils6
    - libkf6kcmutilscore6
    - libkf6kcmutilsquick6
    - libkf6kiocore6
    - libkf6kiofilewidgets6
    - libkf6kiogui6
    - libkf6kiowidgets6
    - libkf6notifications6
    - libkf6pty6
    - libkf6service6
    - libkf6solid6
    - libkf6sonnetcore6
    - libkf6sonnetui6
    - libkf6syntaxhighlighting6
    - libkf6textwidgets6
    - libkf6wallet6
    - libkf6widgetsaddons6
    - libkf6windowsystem6
    - libkf6xmlgui6
    - libkirigami6
    - libkirigamidelegates6
    - libkirigamidialogs6
    - libkirigamilayouts6
    - libkirigamiplatform6
    - libkirigamiprimitives6
    - libkirigamiprivate6
    - liblcms2-2
    - libldap2
    - libldb2
    - liblerc4
    - liblmdb0
    - libltdl7
    - libmbedcrypto16
    - libmd4c0
    - libminizip1t64
    - libmp3lame0
    - libmpg123-0t64
    - libmtdev1t64
    - libmtp9t64
    - libnghttp3-9
    - libngtcp2-16
    - libngtcp2-crypto-gnutls8
    - libnice10
    - libnorm1t64
    - libnspr4
    - libnss3
    - libnuma1
    - libogg0
    - libopenexr-3-1-30
    - libopenjp2-7
    - libopenmpt0t64
    - libopus0
    - liborc-0.4-0t64
    - libpcre2-16-0
    - libpgm-5.3-0t64
    - libphonon4qt6-4t64
    - libplasmaactivities6
    - libplasmaactivitiesstats1
    - libplist-2.0-4
    - libpng16-16t64
    - libpolkit-agent-1-0
    - libpolkit-gobject-1-0
    - libpolkit-qt6-1-1
    - libproxy1v5
    - libpulse-mainloop-glib0
    - libpulse0
    - libqt6core5compat6
    - libqt6core6t64
    - libqt6dbus6
    - libqt6gui6
    - libqt6multimedia6
    - libqt6multimediawidgets6
    - libqt6network6
    - libqt6opengl6
    - libqt6positioning6
    - libqt6printsupport6
    - libqt6qml6
    - libqt6qmlmeta6
    - libqt6qmlmodels6
    - libqt6qmlworkerscript6
    - libqt6quick3d6
    - libqt6quick3druntimerender6
    - libqt6quick3dutils6
    - libqt6quick6
    - libqt6quickcontrols2-6
    - libqt6quickshapes6
    - libqt6quicktemplates2-6
    - libqt6quickwidgets6
    - libqt6shadertools6
    - libqt6spatialaudio6
    - libqt6sql6
    - libqt6sql6-sqlite
    - libqt6svg6
    - libqt6texttospeech6
    - libqt6waylandclient6
    - libqt6waylandcompositor6
    - libqt6widgets6
    - libqt6wlshellintegration6
    - libqt6xml6
    - librabbitmq4
    - librav1e0.8
    - librist4
    - librtmp1
    - libsasl2-2
    - libsharpyuv0
    - libshine3
    - libsm6
    - libsmbclient0
    - libsnappy1v5
    - libsndfile1
    - libsodium23
    - libsoup-3.0-0
    - libsoxr0
    - libspeex1
    - libsqlite3-0
    - libsquashfuse0
    - libsrt1.5-gnutls
    - libssh-4
    - libssh2-1t64
    - libsvtav1enc2
    - libswresample5
    - libswscale8
    - libtag2
    - libtalloc2
    - libtdb1
    - libtevent0t64
    - libtheoradec2
    - libtheoraenc2
    - libtiff6
    - libts0t64
    - libtwolame0
    - libudfread3
    - libusb-1.0-0
    - libusbmuxd-2.0-7
    - libva-drm2
    - libva-x11-2
    - libva2
    - libvdpau1
    - libvorbis0a
    - libvorbisenc2
    - libvorbisfile3
    - libvpl2
    - libvpx11
    - libwacom9
    - libwayland-server0
    - libwbclient0
    - libwebpmux3
    - libx264-165
    - libx265-215
    - libxcb-cursor0
    - libxcb-icccm4
    - libxcb-image0
    - libxcb-keysyms1
    - libxcb-render-util0
    - libxcb-res0
    - libxcb-shape0
    - libxcb-util1
    - libxcb-xinput0
    - libxcb-xkb1
    - libxcomposite1
    - libxdamage1
    - libxdgutilsbasedir1.0.1
    - libxdgutilsdesktopentry1.0.1
    - libxfixes3
    - libxkbcommon-x11-0
    - libxkbcommon0
    - libxkbfile1
    - libxml2-16
    - libxslt1.1
    - libxvidcore4
    - libzmq5
    - libzvbi0t64
    - maui-manager
    - mauikit
    - mauikit-archiver
    - mauikit-filebrowsing
    - ocl-icd-libopencl1
    - qml6-module-org-kde-kirigami
    - qml6-module-org-kde-sonnet
    - qml6-module-qtcore
    - qml6-module-qtmultimedia
    - qml6-module-qtqml
    - qml6-module-qtqml-workerscript
    - qml6-module-qtquick-controls
    - qml6-module-qtquick-effects
    - qml6-module-qtquick-layouts
    - qml6-module-qtquick-shapes
    - qml6-module-qtquick-templates
    - qml6-module-qtquick-tooling
    - qml6-module-qtquick-window
    - qml6-module-qtquick3d-spatialaudio
    - qt6-gtk-platformtheme
    - qt6-svg-plugins
    - qt6-wayland
    - samba-libs
    - vvave
    - xkb-data
  runtime: uruntime

apprunconf:
  setpath: "/usr/bin"
  setlibpath: "/usr/lib"
  exec: "/usr/bin/vvave"
  envvars:
    QT_QPA_PLATFORM: "wayland;xcb"
    QT_QPA_PLATFORMTHEME: ""
    QT_PLUGIN_PATH: "$APPDIR/usr/lib/aarch64-linux-gnu/qt5/plugins:$APPDIR/usr/lib/aarch64-linux-gnu/qt6/plugins"
    QT_QML_IMPORT_PATH: "$APPDIR/usr/lib/aarch64-linux-gnu/qt5/qml:$APPDIR/usr/lib/aarch64-linux-gnu/qt6/qml"
    QML_IMPORT_PATH: "$APPDIR/usr/lib/aarch64-linux-gnu/qt6/qml"
    QML2_IMPORT_PATH: "$APPDIR/usr/lib/aarch64-linux-gnu/qt5/qml"
    SESSION_MANAGER: ""
    XKB_CONFIG_ROOT: "$APPDIR/usr/share/X11/xkb"
    XDG_CURRENT_DESKTOP: "KDE"
    KDE_FULL_SESSION: "true"
    KDE_SESSION_VERSION: "6"
    XDG_CONFIG_DIRS: "$HOME/.config/kdedefaults:/etc/xdg"
    LD_LIBRARY_PATH: "$APPDIR/usr/lib/aarch64-linux-gnu/libproxy:$APPDIR/usr/lib/aarch64-linux-gnu/pulseaudio"
  extra_rpaths:
    - "$ORIGIN/../../../usr/lib/aarch64-linux-gnu/libproxy"
    - "$ORIGIN/../../../usr/lib/aarch64-linux-gnu/pulseaudio"
  prebuild_commands:
    - "cd $APPDIR/usr/lib/aarch64-linux-gnu && ln -sv libMauiKit4.so.4.0.2 libMauiKit4.so.4 && cd -"
    - "cd $APPDIR/usr/lib/aarch64-linux-gnu && ln -sv libMauiMan4.so.4.0.2 libMauiMan4.so.4 && cd -"
    - "cd $APPDIR/usr/lib/aarch64-linux-gnu && ln -sv libMauiKitFileBrowsing4.so.4.0.2 libMauiKitFileBrowsing4.so.4 && cd -"
    - "rm -f $APPDIR/usr/share/metainfo/org.kde.vvave.appdata.xml"

sandbox:
  type: bwrap
  dev: true
  proc: true
  tmpfs: true
  unshare-user: true
  unshare-uts: true
  cap-drop-all: true
  die-with-parent: true
  bind:
    - "$HOME:$HOME"
    - ~/.config:~/.config
    - ~/.local:~/.local
    - "$XDG_RUNTIME_DIR:$XDG_RUNTIME_DIR"
    - /dev/shm:/dev/shm
    - /dev/dri:/dev/dri
  ro-bind:
    - "$APPDIR:$APPDIR"
    - /lib:/lib
    - /lib64:/lib64
    - /usr:/usr
    - /etc/fonts:/etc/fonts
    - /etc/xdg:/etc/xdg
    - /etc/alternatives:/etc/alternatives
  bwrap_env:
    - HOME: "$HOME"
    - LANG: "en_US.UTF-8"
    - XDG_RUNTIME_DIR: "$XDG_RUNTIME_DIR"
    - WAYLAND_DISPLAY: "$WAYLAND_DISPLAY"
  bwrap_unset-env:
    - DISPLAY
    - QT_QPA_PLATFORMTHEME

integration:
  type: gui
